version: '3.9'

services:
  my-news-service01-test:
    image: ${TEST_CONTAINER_IMAGE}
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:${MSR_LICENSE_MOUNT_POINT}
      - ./application.properties:${APP_PROPS_MOUNT_POINT}
    environment:
      - SAG_IS_LICENSE_FILE=${MSR_LICENSE_MOUNT_POINT}
      - SAG_IS_CONFIG_PROPERTIES=${APP_PROPS_MOUNT_POINT}
      - IS_ADMIN_PWD
      - SMTP_HOST_NAME
      - SMTP_HOST_PORT
      - SMTP_USER_EMAIL
      - SMTP_USER_PASS
      # NewsAPI service
      - NEWSAPI_BASE_URL
      - NEWS_API_KEY