# Example Software AG Products containers building pipeline
# Fork and specialize according to need

trigger:
- main

pool:
  name: SpxWorkshopAgents
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-cvm:latest

  steps:

    # In general the provided code is reusable and will be templatized when mature enough
    # Write here the job specific parameters for now
    # This job is specialized for MSR/1015/lean
    - script: chmod u+x ./buildScripts/*.sh
      displayName: "Grant shell execution permissions"

    # Some variables must be propagated accross steps
    - script: ./buildScripts/01.setJobInitialVariables.sh
      displayName: 'Job Locals'
    
    # update ubuntu machine
    - script: ./buildScripts/02.prepareAgentMachine.sh
      displayName: 'System software preparation'

    # Service Principal is required to connect to ACR
    - task: DownloadSecureFile@1
      name: acrSpCredentials
      displayName: 'Download Service Principal Credentials'
      inputs:
        secureFile: 'acr.sp.credentials.sh'

    # Containerize
    - script: ./buildScripts/04.build.sh
      displayName: 'Build'
