version: '3.9'

services:
  msr-lean:
    image: ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_REPOSITORY}:${CONTAINER_IMAGE_TAG}
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:${MSR_LICENSE_MOUNT_POINT}
      - ./application.properties:${APP_PROPS_MOUNT_POINT}
      - ./local/:/mnt/local/
      - ./scripts/:/mnt/scripts/
      - ../../code/is-packages/MyNewsService:${GUEST_IS_HOME}/packages/MyNewsService
    environment:
      - SAG_IS_LICENSE_FILE=${MSR_LICENSE_MOUNT_POINT}
      - SAG_IS_CONFIG_PROPERTIES=${APP_PROPS_MOUNT_POINT}
      - IS_ADMIN_PWD
    ##entrypoint: /mnt/scripts/entrypoint.sh